[2022-10-14T00:40:30.406+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DAG_cines.get_data manual__2022-10-14T00:40:29.395731+00:00 [queued]>
[2022-10-14T00:40:30.417+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DAG_cines.get_data manual__2022-10-14T00:40:29.395731+00:00 [queued]>
[2022-10-14T00:40:30.418+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-14T00:40:30.421+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-14T00:40:30.422+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-14T00:40:30.432+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_data> on 2022-10-14 00:40:29.395731+00:00
[2022-10-14T00:40:30.437+0000] {standard_task_runner.py:54} INFO - Started process 106 to run task
[2022-10-14T00:40:30.445+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DAG_cines', 'get_data', 'manual__2022-10-14T00:40:29.395731+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/DD_template.py', '--cfg-path', '/tmp/tmp8cl7mst7']
[2022-10-14T00:40:30.446+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask get_data
[2022-10-14T00:40:30.448+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/DD_template.py
[2022-10-14T00:40:30.709+0000] {task_command.py:384} INFO - Running <TaskInstance: DAG_cines.get_data manual__2022-10-14T00:40:29.395731+00:00 [running]> on host 46d28f7b750d
[2022-10-14T00:40:30.760+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DAG_cines
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T00:40:29.395731+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-14T00:40:29.395731+00:00
[2022-10-14T00:40:32.395+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DD_template.py", line 21, in get_data
    url = config('DATOS_CINES')
  File "/home/airflow/.local/lib/python3.7/site-packages/decouple.py", line 243, in __call__
    return self.config(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/decouple.py", line 105, in __call__
    return self.get(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/decouple.py", line 90, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: DATOS_CINES not found. Declare it as envvar or define a default value.
[2022-10-14T00:40:32.418+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DAG_cines, task_id=get_data, execution_date=20221014T004029, start_date=20221014T004030, end_date=20221014T004032
[2022-10-14T00:40:32.448+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task get_data (DATOS_CINES not found. Declare it as envvar or define a default value.; 106)
[2022-10-14T00:40:32.515+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-14T00:40:32.558+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
