[2022-10-14T14:26:37.741+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DAG_cines.transform_data manual__2022-10-14T14:26:33.401590+00:00 [queued]>
[2022-10-14T14:26:37.748+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DAG_cines.transform_data manual__2022-10-14T14:26:33.401590+00:00 [queued]>
[2022-10-14T14:26:37.749+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-14T14:26:37.750+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-14T14:26:37.751+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-14T14:26:37.759+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_data> on 2022-10-14 14:26:33.401590+00:00
[2022-10-14T14:26:37.763+0000] {standard_task_runner.py:54} INFO - Started process 83 to run task
[2022-10-14T14:26:37.766+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DAG_cines', 'transform_data', 'manual__2022-10-14T14:26:33.401590+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/DD_template.py', '--cfg-path', '/tmp/tmpob2wvr0r']
[2022-10-14T14:26:37.767+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask transform_data
[2022-10-14T14:26:37.768+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/DD_template.py
[2022-10-14T14:26:37.922+0000] {task_command.py:384} INFO - Running <TaskInstance: DAG_cines.transform_data manual__2022-10-14T14:26:33.401590+00:00 [running]> on host 9cf83b5ba954
[2022-10-14T14:26:37.963+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DAG_cines
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T14:26:33.401590+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-14T14:26:33.401590+00:00
[2022-10-14T14:26:38.129+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DD_template.py", line 84, in transform_data
    from libs.functions import get_col_of_insterest, clean_columns
ModuleNotFoundError: No module named 'libs'
[2022-10-14T14:26:38.142+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DAG_cines, task_id=transform_data, execution_date=20221014T142633, start_date=20221014T142637, end_date=20221014T142638
[2022-10-14T14:26:38.154+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 99 for task transform_data (No module named 'libs'; 83)
[2022-10-14T14:26:38.182+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-14T14:26:38.208+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
